title = "My Terminal Velocity Blog"
description = "A blazingly fast tech blog"
base_url = "http://localhost:8000"

[author]
name = "Anonymous"
email = "author@example.com"

[build]
verbose = true
# The following are relative to the site path
output_dir = "dist"
posts_dir = "posts"
templates_dir = "templates"
static_dir = "static"

[server]
port = 8000
